/**
 * Parse Betaflight CLI dump format
 * @param {string} text - CLI dump text
 * @returns {Object} Parsed settings as key-value pairs
 */
export function parseCLI(text) {
  const settings = {};
  const lines = text.split('\n');

  for (const line of lines) {
    // Match pattern: [set] parameter_name = value
    // Support optional 'set' prefix and varied spacing
    const match = line.match(/^\s*(?:set\s+)?([a-z_]+)\s*=\s*(.+?)\s*$/i);
    if (match) {
      const key = match[1].toLowerCase();
      const value = match[2].trim();
      // Store last occurrence (overwrites previous)
      settings[key] = value;
    }
  }

  return settings;
}

/**
 * Generate Betaflight CLI commands from a profile
 * @param {Object} profile - Profile object with rates and throttle settings
 * @returns {string} CLI commands
 */
export function generateCLI(profile) {
  const commands = [
    '# Betaflight Rate Profile Configuration',
    '# Generated by FPV Rate Profile Comparison Tool',
    ''
  ];

  if (profile.name) {
    commands.push(`# Profile: ${profile.name}`);
    commands.push('');
  }

  commands.push(
    '# Rate Type',
    'set rates_type = ACTUAL',
    '',
    '# Roll Rates',
    `set roll_rc_rate = ${profile.rates.roll.center}`,
    `set roll_rate = ${profile.rates.roll.maxRate}`,
    `set roll_expo = ${profile.rates.roll.expo}`,
    '',
    '# Pitch Rates',
    `set pitch_rc_rate = ${profile.rates.pitch.center}`,
    `set pitch_rate = ${profile.rates.pitch.maxRate}`,
    `set pitch_expo = ${profile.rates.pitch.expo}`,
    '',
    '# Yaw Rates',
    `set yaw_rc_rate = ${profile.rates.yaw.center}`,
    `set yaw_rate = ${profile.rates.yaw.maxRate}`,
    `set yaw_expo = ${profile.rates.yaw.expo}`,
    '',
    '# Throttle',
    `set thr_mid = ${profile.throttle.mid}`,
    `set thr_expo = ${profile.throttle.expo}`,
    '',
    'save'
  );

  return commands.join('\n');
}
